@echo off
set "dest=%SystemDrive%\Program Files\MPV"
if not exist "%dest%" mkdir "%dest%"
if not exist "%dest%" exit

powershell -Command "Invoke-WebRequest -Uri 'https://github.com/serbinskis/delphi/raw/refs/heads/master/MPV/mpv.exe' -OutFile '%dest%\mpv.exe'"
set "menu=%SystemDrive%\ProgramData\Microsoft\Windows\Start Menu\Programs\MPV"
if not exist "%menu%" mkdir "%menu%"

echo linkFile = "%menu%\mpv.lnk" > "%TEMP%\createShortcut.vbs"
echo Set objectLink = WScript.CreateObject("WScript.Shell").CreateShortcut(linkFile) >> "%TEMP%\createShortcut.vbs"
echo objectLink.TargetPath = "%SystemDrive%\Program Files\MPV\mpv.exe" >> "%TEMP%\createShortcut.vbs"
echo objectLink.Save >> "%TEMP%\createShortcut.vbs"
cscript "%TEMP%\createShortcut.vbs" >nul
del "%TEMP%\createShortcut.vbs"

powershell -Command "Invoke-WebRequest -Uri 'https://github.com/serbinskis/delphi/raw/refs/heads/master/MPV/resources/mpv.reg' -OutFile '%dest%\mpv.reg'"
reg import "%dest%\mpv.reg" >nul 2>nul
del "%dest%\mpv.reg"

powershell -Command "Invoke-WebRequest -Uri 'https://github.com/serbinskis/delphi/raw/refs/heads/master/MPV/resources/association.exe' -OutFile '%dest%\association.exe'"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.it" ".it"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.s3m" ".s3m"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.voc" ".voc"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.xm" ".xm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ac3" ".ac3"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ac3" ".a52"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.eac3" ".eac3"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mlp" ".mlp"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.dts" ".dts"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.dts-hd" ".dts-hd"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.dts-hd" ".dtshd"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.true-hd" ".true-hd"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.true-hd" ".thd"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.true-hd" ".truehd"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.true-hd" ".thd+ac3"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.tta" ".tta"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.pcm" ".pcm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.wav" ".wav"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.aiff" ".aiff"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.aiff" ".aif"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.aiff" ".aifc"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.amr" ".amr"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.awb" ".awb"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.au" ".au"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.au" ".snd"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.lpcm" ".lpcm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.yuv" ".yuv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.y4m" ".y4m"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ape" ".ape"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.wv" ".wv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.shn" ".shn"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".m2ts"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".m2t"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".mts"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".mtv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".ts"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".tsv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".tsa"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".tts"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m2ts" ".trp"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.adts" ".adts"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.adts" ".adt"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpa" ".mpa"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpa" ".m1a"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpa" ".m2a"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpa" ".mp1"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpa" ".mp2"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mp3" ".mp3"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mpeg"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mpg"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mpe"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mpeg2"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".m1v"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".m2v"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mp2v"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mpv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mpv2"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".mod"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg" ".tod"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.vob" ".vob"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.vob" ".vro"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.evob" ".evob"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.evob" ".evo"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg4" ".mpeg4"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg4" ".m4v"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg4" ".mp4"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg4" ".mp4v"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mpeg4" ".mpg4"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m4a" ".m4a"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.aac" ".aac"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.h264" ".h264"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.h264" ".avc"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.h264" ".x264"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.h264" ".264"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.hevc" ".hevc"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.hevc" ".h265"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.hevc" ".x265"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.hevc" ".265"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.flac" ".flac"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.oga" ".oga"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.oga" ".ogg"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.opus" ".opus"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.spx" ".spx"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ogv" ".ogv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ogv" ".ogm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ogx" ".ogx"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mkv" ".mkv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mk3d" ".mk3d"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mka" ".mka"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.webm" ".webm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.weba" ".weba"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.avi" ".avi"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.avi" ".vfw"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.divx" ".divx"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.3iv" ".3iv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.xvid" ".xvid"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.nut" ".nut"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.flic" ".flic"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.flic" ".fli"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.flic" ".flc"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.nsv" ".nsv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.gxf" ".gxf"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.mxf" ".mxf"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.wma" ".wma"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.wm" ".wm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.wmv" ".wmv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.asf" ".asf"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.dvr-ms" ".dvr-ms"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.dvr-ms" ".dvr"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.wtv" ".wtv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.dv" ".dv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.dv" ".hdv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.flv" ".flv"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.f4v" ".f4v"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.f4a" ".f4a"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.qt" ".qt"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.qt" ".mov"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.hdmov" ".hdmov"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.rm" ".rm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.rmvb" ".rmvb"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ra" ".ra"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ra" ".ram"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.3ga" ".3ga"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.3ga2" ".3ga2"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.3gpp" ".3gpp"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.3gpp" ".3gp"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.3gp2" ".3gp2"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.3gp2" ".3g2"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.ay" ".ay"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.gbs" ".gbs"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.gym" ".gym"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.hes" ".hes"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.kss" ".kss"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.nsf" ".nsf"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.nsfe" ".nsfe"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.sap" ".sap"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.spc" ".spc"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.vgm" ".vgm"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.vgz" ".vgz"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m3u" ".m3u"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.m3u" ".m3u8"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.pls" ".pls"
start /MIN /WAIT "" "%dest%\association.exe" "io.mpv.cue" ".cue"
del "%dest%\association.exe"
